# Generated by Django 4.2.7 on 2024-11-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_menuitem_options_menuitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_covers/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
