# Generated by Django 4.2.7 on 2024-11-29 23:14

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_restaurant_cover_image_restaurant_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accent_color',
            field=colorfield.fields.ColorField(default='#17a2b8', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='background_color',
            field=colorfield.fields.ColorField(default='#ffffff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='font_family',
            field=models.CharField(choices=[('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat')], default='Roboto', max_length=50),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu_style',
            field=models.CharField(choices=[('modern', 'Modern Grid'), ('classic', 'Classic List'), ('elegant', 'Elegant Cards'), ('minimal', 'Minimal')], default='modern', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#6c757d', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='text_color',
            field=colorfield.fields.ColorField(default='#212529', image_field=None, max_length=25, samples=None),
        ),
    ]
