# Generated by Django 4.2.7 on 2024-12-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_delete_menutheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='restaurant_qr_codes/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='logos/'),
        ),
    ]
