# Generated by Django 4.2.7 on 2024-12-04 00:11

from django.db import migrations, models
import restaurants.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_restaurant_qr_code_alter_menuitem_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.menu_item_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.restaurant_cover_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.restaurant_logo_path),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=restaurants.models.restaurant_qr_path),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to=restaurants.models.table_qr_path),
        ),
    ]
