# Generated by Django 4.2.7 on 2024-12-04 10:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_alter_menuitem_image_alter_restaurant_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='accent_color',
            field=models.CharField(default='#17a2b8', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_image'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='primary_color',
            field=models.CharField(default='#007bff', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_code'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='secondary_color',
            field=models.CharField(default='#6c757d', max_length=7),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='text_color',
            field=models.CharField(default='#212529', max_length=7),
        ),
        migrations.AlterField(
            model_name='table',
            name='qr_code',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='qr_code'),
        ),
    ]
